### ISSUE TITLE
Resetting password added a new account instead

### ISSUE THREAD

**Issue by StenPett** [EmissarySocial/bandwagon#16]
Trying to resolve another issue, I cleared my cookies ans site data, but I had forgotten my password so I reset it. But when setting the new password, I was redirected to the new account sign-up instead of returning to my account. Completing the setup created a new artist page, but I've lost access to my old artist page. There are now two "St Midium" pages on bandwagon.fm. The one that has an uploaded album is the old one.

**Comment by benpate** [comment]
Oh no!  Thanks for the bug report. I have not seen this behavior before, but did just make some changes to the signup process, so it’s possible that this bug was introduced then. 

I’ll take a look at this, figure out what’s going on, and work to get a fix out for it tonight. 

Do you also need help with your password?

**Comment by StenPett** [comment]
Thank you for the quick reply.

Yes, I still need help with the password on the actual account (stmidium). The st-midium account can be deleted, but I couldn't find an easy way to do that.

**Comment by benpate** [comment]
Ok. I’ve got you. I’ll get your password reset later this afternoon.

**Comment by benpate** [comment]
Hey, I've tried this on my own account, but it's still linking to my correct account. I'm going to do a few more tests on my end, but for now I've just removed the duplicate profile and sent a welcome / password reset email to you that should get you in.  If you need any more help with this (or anything else) please send me a note!
