### ISSUE TITLE
Additional uploads for albums

### ISSUE THREAD

**Issue by benpate** [EmissarySocial/bandwagon#2]
If an album includes things like PDF files with liner notes, lyrics, illustrations, photos and so on, or other images like additional PNGs or JPGs etc which are part of the album package, can those be added?

**Comment by docpop** [comment]
I love this idea, if it isn't too much of a hassle to implement. I'd love to include .nan files for some of my albums. These are files that will open in Nanoloop For Mobile, so people can remix my songs. It' a niche thing, but would be cool to include.

**Comment by benpate** [comment]
Hey.  This is done and on the server now.  Just go to your album and look for the "Downloads" button on the left hand side
